basePath: /wifidog
consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
host: localhost:8081
info:
  contact:
    email: gukaiqiang@gmail.com
    name: goauth
  description: A basic example of a WiFiDog Auth-server API implemented with goa
  title: The virtual wine cellar
  version: ""
paths:
  /ping/{args}:
    get:
      description: answer wifidog ping GET-Request
      operationId: ping#AnswerPing
      parameters:
      - in: path
        name: args
        required: true
        type: string
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: AnswerPing ping
      tags:
      - ping
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
