// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/KerwinKoo/goauth/design
// --out=$(GOPATH)/src/github.com/KerwinKoo/goauth
// --version=v1.1.0
//
// API "goauth": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app
